### 1️⃣ Create a New Batch
POST http://localhost:3000/api/batches
Content-Type: application/json

{
  "product_id": "2528a332-ca88-4c07-bec9-4f62696295c6",
  "farmer_id": "dbd62bb4-618d-454a-9a90-523317ab3734",
  "initial_qty_kg": 50,
  "unit": "KG",
  "harvest_date": "2025-09-16T12:29:43.932Z",
  "geo_lat": 23.0225,
  "geo_lon": 72.5714,
  "location_name": "Thiruninravur High Road, Thiruninravur, Thiruvallur District, Tamil Nadu, India",
  "meta_hash": "QmXyzCornGluten123abc",
  "organic": true,
  "price_per_unit": 65.50
}


### 2️⃣ Update Batch Status
PATCH http://localhost:3000/api/batches/3f7856aa-a7b3-4bda-b276-cbb5aeda1023/status
Content-Type: application/json

{
  "status": "LISTED"
}

### 3️⃣ Split Batch
POST http://localhost:3000/api/batches/4dfef5c8-15df-4b42-bc66-4914c3b1db41/split
Content-Type: application/json

{
  "split_qty": 25,
  "unit": "KG"
}

### 4️⃣ Merge Batches
POST http://localhost:3000/api/batches/merge
Content-Type: application/json

{
  "batch_ids": [
    "4dfef5c8-15df-4b42-bc66-4914c3b1db41",
    "8c2a70b6-9414-41c2-844e-e8cd1284595d"
  ],
  "new_batch_code": "MERGED-BATCH-001"
}

### 5️⃣ Update Harvest/Location/Meta Info (can update organic too)
PATCH http://localhost:3000/api/batches/d5c23cee-c10d-4f8b-826f-72d0e369058e
Content-Type: application/json

{
  "geo_lat": 23.0300,
  "geo_lon": 72.5800,
  "location_name": "New Warehouse Location, Thiruvallur, Tamil Nadu, India",
  "meta_hash": "QmUpdatedMetaHash123xyz",
  "organic": false
}

### 6️⃣ Anchor Metadata (Blockchain Simulation)
PATCH http://localhost:3000/api/batches/d5c23cee-c10d-4f8b-826f-72d0e369058e/anchor
Content-Type: application/json

{
  "meta_hash": "QmXyzCornGluten123abc"
}

### 🔎 Get all available batches (ONDC Discovery)
GET http://localhost:3000/api/batches
Accept: application/json

### 🔎 Get batches by product type
GET http://localhost:3000/api/batches?product_type=herbicide
Accept: application/json

### 🔎 Get batches by farmer
GET http://localhost:3000/api/batches?farmer_id=dbd62bb4-618d-454a-9a90-523317ab3734
Accept: application/json

### 🔎 Get batches by minimum available quantity
GET http://localhost:3000/api/batches?min_qty=50
Accept: application/json

### 🔎 Get batches by multiple filters (product type + min qty)
GET http://localhost:3000/api/batches?product_type=herbicide&min_qty=50
Accept: application/json

### 🔎 Search by product name (case-insensitive, partial match)
GET http://localhost:3000/api/batches?product_name=apple
Accept: application/json

### 🔎 Optional: Filter by organic batches
GET http://localhost:3000/api/batches?organic=true
Accept: application/json


### 🔎 Optional: Filter by product id
GET http://localhost:3000/api/batches?product_id=2528a332-ca88-4c07-bec9-4f62696295c6