POST http://localhost:3000/bpp/on_init
Content-Type: application/json

{
  "context": {
    "domain": "ondc:agri",
    "country": "IND",
    "action": "init",
    "core_version": "1.2.0",
    "bap_id": "bap.agri.app",
    "bap_uri": "https://bap.agri.app",
    "transaction_id": "REPLACE_WITH_TXN_ID",
    "message_id": "REPLACE_WITH_TXN_ID",
    "timestamp": "2025-08-06T12:00:00.000Z"
  },
  "message": {
    "order": {
      "provider": {
        "id": "910d34a9-b9c0-489a-b7e1-73657d0e4503"
      },
      "items": [
        {
          "id": "8620b9d9-2c8d-4309-a6dc-77d34d0d324c",
          "quantity": {
            "count": 1
          },
          "fulfillment_id": "d2c6b0c9-5a5c-44de-8c3f-75875100a6f2"
        },
        {
          "id": "fba521cd-15db-42fe-b3da-8deb336576ed",
          "quantity": {
            "count": 2
          },
          "fulfillment_id": "d2c6b0c9-5a5c-44de-8c3f-75875100a6f2"
        },
        {
          "id": "fe3d48d4-099a-49e3-86d6-140f2e37d515",
          "quantity": {
            "count": 3
          },
          "fulfillment_id": "d2c6b0c9-5a5c-44de-8c3f-75875100a6f2"
        }
      ],
      "fulfillment": {
        "end": {
          "location": {
            "gps": "17.3850,78.4867",
            "address": "Sector 14, Lucknow"
          }
        }
      }
    }
  }
}
