

### Search inventory
POST http://192.168.67.186:3000/bpp/on_search
Content-Type: application/json
# Authorization: Bearer YOUR_TOKEN_HERE

{
  "intent": {
    "item": {
      "descriptor": {
        "name": ""
      }
    },
    "category": {
    "id": "herbicide"
    },
    "fulfillment": {
      "end": {
        "location": {
          "gps": "23.0225,72.5714"
        }
      }
    }
  },
  "radius": 100
}






