POST http://localhost:3000/bpp/on_select
Content-Type: application/json

{

  "context": {
        "domain": "ondc:agri",
        "action": "select",
        "core_version": "1.2.0",
        "country": "IND",
        "city": "std:080",
        "transaction_id": "txnId",
        "message_id": "txnId",
        "timestamp": "2024-07-11T15:30:00.000Z",
        "bap_id": "bap.agri.app",
        "bap_uri": "https://bap.agri.app"
      },
  "message": {
    "catalog": {
      "items": [
          {"id": "9352287f-8885-4d5e-8e9d-d7615841db79"}
      ]
    }
  }
}