
### Get Top 3 Categories to Cart
GET http://localhost:5000/cart/getcategories
Content-Type: application/json

{
  "user_id": "a985baac-9028-4dc1-bbd9-a6f3aae49ef5"
}

### View Cart
Get http://localhost:5000/cart/view/a985baac-9028-4dc1-bbd9-a6f3aae49ef5
Content-Type: application/json'

### Add Item to Cart
POST http://localhost:5000/cart/add
Content-Type: application/json

{
  {
  "user_id": "a985baac-9028-4dc1-bbd9-a6f3aae49ef5",
  "bpp_id": "agri.bpp",
  "bpp_product_id": "34799eb9-d699-4433-875b-a8bd4bc0a12a",
  "provider_id": "910d34a9-b9c0-489a-b7e1-73657d0e4503",
  "provider_name": "Arjun Reddy",
  "provider_address": "Banjara Hills, Hyderabad",
  "fulfillment_id": "FUL003",
  "item_name": "Glyphosate 41% SL",
  "quantity": 5,
  "unit_price": 20.00,
  "category": "herbicide",
  "image_url": "https://agribegri.com/productimage/7354035311733221089.webp"
}
}
### delete Item from Cart
DELETE http://localhost:5000/cart/clear
Content-Type:application/json

{
  "user_id": "a985baac-9028-4dc1-bbd9-a6f3aae49ef5"
}

### Update Item in Cart
PUT http://localhost:5000/cart/update
Content-Type: application/json

{
  "user_id": "a985baac-9028-4dc1-bbd9-a6f3aae49ef5",
  "bpp_product_id": "34799eb9-d699-4433-875b-a8bd4bc0a12a",
  "provider_id": "910d34a9-b9c0-489a-b7e1-73657d0e4503",
  "quantity": 10
}